Repository SOM-Timer/som_timer_be, pull requests merged in 2020-10, with the labels that each got.

#8 Add Timers table and connect som_timer db
  api.py
  migrations/README
  migrations/alembic.ini
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/f5ff70ea61d8_.py
Labels: BE, setup

#15 Flask App Structure Build Out
  .gitignore
  api.py
  application/__init__.py
  application/config.py
  application/controllers/exercises.py
  application/controllers/timers.py
  application/models/exercise.py
  application/models/timer.py
  manage.py
  migrations/versions/453de40b8a4e_.py
  requirements.txt
  run.py
  tests/test_exercises.py
  tests/test_timers.py
Labels: BE, enhancement, setup, testing

#20 Seeding Data
  app.py
  migrations/versions/4a855fbde8fa_.py
  requirements.txt
Labels: BE, enhancement, research

#32 Deployment setup
  .travis.yml
Labels: BE, Phase 3, chore, setup

#39 Added query accessibility to rand get request
  README.md
  application/controllers/exercises.py
Labels: BE, Phase 3, bug, enhancement, mvp, testing
